---
- name: Converge
  hosts: all
  vars:
    ingress_manifest_url: "https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml"
  roles:
    - role: ingress_nginx
