---
driver:
  name: podman
platforms:
  - name: instance
    image: quay.io/ansible/ubuntu20.04-ansible:latest
    privileged: true
provisioner:
  name: ansible
lint: |
  set -e
  ansible-lint
verifier:
  name: ansible
