---
 name: Full cluster setup
  hosts: all
  roles:
    - { role: common, tags: ['common'] }
    - { role: preflight, tags: ['preflight'] }
    - { role: kube_master, tags: ['master'] }
    - { role: kube_node, tags: ['node'] }
    - { role: cni_calico, tags: ['network', 'calico'] }
    - { role: ingress_nginx, tags: ['ingress'] }
    - { role: dashboard, tags: ['dashboard'] }
